---
title: Exploring single-cell RNA sequencing using COVID-19 lung data
date: last-modified
date-format: full
author:
  - name:
      given: Pranav Kumar
      family: Mishra
    affiliations:
      - ref: rushsurg
      - ref: rushortho
    corresponding: true
    url: https://drpranavmishra.com
    email: pranav_k_mishra@rush.edu
    orcid: 0000-0001-5219-6269
citation: true
google-scholar: true       
bibliography: references.bib
---

# Exploring single-cell RNA sequencing using COVID-19 lung data

## About

This repository is following an excellent tutorial created by Mark Sanborn  ([\@Sanbiomics](https://www.youtube.com/@sanbomics)) on YouTube [-@sanborn2022]. scRNA-seq data is provided by @melms2021

## Data source

Melms JC, Biermann J, Huang H, Wang Y et al. A molecular single-cell lung atlas of lethal COVID-19. Nature 2021 Jul;595(7865):114-119. PMID: 33915568

``` sh
# Download the data from GEO Accession
wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE171nnn/GSE171524/suppl/GSE171524_RAW.tar

# Extract the files
tar -xf GSE171524_RAW.tar -C ./data/
cd data
gunzip *gz
```

## Python packages required

I prefer the python package manager `mamba`, which is a faster form of the ubiquitous `conda`. 

``` sh
# Install dependencies / libaries
mamba env update --file ./python/environment.yaml  --prune
```
## CPU vs. GPU vs. TPU

Using a GPU substantially increases the computational speed of Single Cell Variation Interface Tools (`scvi-tools`). 8 core CPUs perform about 7 times slower than a Google Colab notebook's free GPU. I have also attempted to run the code on a Google Colab TPU-based environment, as well. However, in my initial tests, the TPU was not detected, and pytorch (via sc)

### Limitations of Google Colab (Free)
Though it is a great service to explore python code, Google Colab does not offer enough computer memory (RAM) to successfully run this dataset, with all samples loaded into adata. In my trial, I was able to combine together 4 lung donor scRNAseq data files into one `adata` variable before running out of memory

### My setup
I am running this code on two separate machines for testing purposes.

#### HP Z820
CPU: 16 core, 32 threads
RAM: 128 GB
GPU: nVidia GeForce RTX 3060

Hypervisor: Windows 10 Pro
Virtual Machine: Ubuntu 22.04, with 14 cores, 80GB RAM passed in

::: {.callout-note}
I am currently having difficulty passing in the GPU into the VM. I plan to evaluate Proxmox as a hypervisor for an easier GPU passthrough
:::

### Tiny Machine
CPU: i5-8500 CPU @ 3.00GHz
RAM: 16 GB

Hypervisor: Proxmox 7.4
Virtual Machine: Ubuntu 22.04,

::: {.callout-note}
```sh
You can check your machine's hardware with
cat /proc/cpuinfo

sudo dmidecode --type memory | less
```
:::

## SCVI

### Recommendations from developers

- For scVI, we recommend anywhere from 1,000 to 10,000 HVGs, but it will be context-dependent.